### ISSUE TITLE
Implement inaSpeechSegmenter wrapper as a Dockerized CLAMS app

### ISSUE THREAD

**Issue by angus-lherrou** [clamsproject/app-inaspeechsegmenter-wrapper#1]
Work on this is being done in the develop branch.

To do:

- [ ] Ensure that CUDA support is correctly configured in the Docker image and runs in CLAMS Galaxy
- [ ] Ensure CPU-only behavior works correctly (or decide to disclaim against CPU-only usage)

**Comment by angus-lherrou** [comment]
The app runs and produces results with the demo script on my machine but it may not be portable.

**Comment by keighrim** [comment]
All sovled via #4.
