### ISSUE TITLE
Replace `git clone` target in Dockerfile with v0.2.0 tag once app-audio-segmenter is updated

### ISSUE THREAD

**Issue by angus-lherrou** [clamsproject/app-inaspeechsegmenter-wrapper#2]
https://github.com/clamsproject/app-ina-segmenter/blob/ae1c2afd9e6216308d7415169a83bb3abdf810ac/Dockerfile#L30

Change this line to:

```
RUN git clone --depth 1 --branch v0.2.0 https://github.com/clamsproject/app-audio-segmenter.git app_audio_segmenter
```

once clamsproject/app-audio-segmenter#2 is merged and the commit for that version has been tagged as `v0.2.0`.

**Comment by keighrim** [comment]
I will drop this idea, because I think ina-segmenter should be standalone in terms of at least not depending on other *apps*. We might want to consider factor some common behaviors up into the `clams-python` SDK in the future.
