### ISSUE TITLE
add runtime parameter to ignore all "short" segments

### ISSUE THREAD

**Issue by keighrim** [clamsproject/app-inaspeechsegmenter-wrapper#7]
### New Feature Summary

When a "positive" segment is too short, for example music shorter than 1 second, it doesn't make a lot of sense. We'd like to enable users to set a certain threshold for the minimum positive duration to de-noise output MMIF, with a reasonable default value.

**Comment by kla7** [comment]
This feature was addressed via the `minDuration` (now `minTFDuration`) parameter added in commit 882e836.
